name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Run on Ubuntu virtual machines

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Update version as needed
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3  # Update version as needed
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-app-name:latest